name: reusable_testing

on:
  workflow_call:
    inputs:
      artifact_name:
        description: 'The name of the tarantool build artifact'
        default: ubuntu-focal
        required: false
        type: string

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
      - name: 'Clone the smtp module'
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/smtp

      - name: 'Download the tarantool build artifact'
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.artifact_name }}

      - name: 'Install tarantool'
        # TODO(ylobankov): Install package dependencies. Now we're lucky: all
        # dependencies are already there.
        run: sudo dpkg -i tarantool*.deb

      - run: cmake . && make
      - run: make check
